# Generated by Django 6.0.3 on 2026-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('stream_identifier', models.CharField(max_length=255, unique=True)),
                ('stream_url', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('current_state', models.CharField(choices=[('offline', '离线'), ('connecting', '连接中'), ('online', '在线'), ('disconnected', '已断开'), ('error', '异常')], default='offline', max_length=16)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
