// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScpCv.Infrastructure.Persistence;

#nullable disable

namespace ScpCv.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    partial class ControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ScpCv.Domain.Model.ArtifactManifest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "SourceDigest", "RecipeVersion", "RelativePath")
                        .IsUnique();

                    b.ToTable("artifact_manifests", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.BackgroundAudioPlaylistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("StateId");

                    b.HasIndex("SortOrder", "Id");

                    b.ToTable("background_audio_playlist_items", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.BackgroundAudioState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandArgsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LoopEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSourceId");

                    b.ToTable("background_audio_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_background_audio_state_singleton", "Id = 1");

                            t.HasCheckConstraint("CK_background_audio_state_volume", "Volume >= 0 AND Volume <= 100");
                        });
                });

            modelBuilder.Entity("ScpCv.Domain.Model.CommandRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ConsumerInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Deadline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeaseExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultEvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TargetSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.HasIndex("TargetKind", "TargetId")
                        .IsUnique()
                        .HasFilter("Status = 'Processing'");

                    b.HasIndex("TargetKind", "TargetId", "TargetSequence")
                        .IsUnique();

                    b.HasIndex("TargetKind", "TargetId", "Status", "TargetSequence");

                    b.ToTable("command_records", null, t =>
                        {
                            t.HasCheckConstraint("CK_command_records_target", "(TargetKind = 'Display' AND TargetId >= 1 AND TargetId <= 4) OR (TargetKind = 'Audio' AND TargetId = 1)");
                        });
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("media_folders", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaPreparationJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Deadline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDigest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("SourceId", "SourceDigest", "Kind", "RecipeVersion")
                        .IsUnique();

                    b.ToTable("media_preparation_jobs", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentDigest")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepAlive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FolderId");

                    b.HasIndex("StreamIdentifier");

                    b.ToTable("media_sources", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.OfficeOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("TEXT");

                    b.Property<long>("Deadline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HostEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCommandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SlotEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("ParentCommandId");

                    b.HasIndex("ParentJobId");

                    b.HasIndex("Status", "Deadline");

                    b.ToTable("office_operations", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.PlaybackSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualAdapterKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActualSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CleanupPending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandArgsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentSlide")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DesiredGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LoopEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediaSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ObservedGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaybackState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlayerLastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PositionMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetDisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSlides")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaSourceId");

                    b.HasIndex("WindowId")
                        .IsUnique();

                    b.ToTable("playback_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_playback_sessions_volume", "Volume >= 0 AND Volume <= 100");

                            t.HasCheckConstraint("CK_playback_sessions_window", "WindowId >= 1 AND WindowId <= 4");
                        });
                });

            modelBuilder.Entity("ScpCv.Domain.Model.PptResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlideImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeakerNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "PageIndex")
                        .IsUnique();

                    b.ToTable("ppt_resources", null, t =>
                        {
                            t.HasCheckConstraint("CK_ppt_resources_page_index", "PageIndex >= 1");
                        });
                });

            modelBuilder.Entity("ScpCv.Domain.Model.RuntimeGroupControl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ExplicitStartRequestId")
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("runtime_group_control", null, t =>
                        {
                            t.HasCheckConstraint("CK_runtime_group_control_singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("ScpCv.Domain.Model.RuntimeState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BigScreenMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VolumeMuted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("runtime_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_runtime_state_singleton", "Id = 1");

                            t.HasCheckConstraint("CK_runtime_state_volume", "VolumeLevel >= 0 AND VolumeLevel <= 100");
                        });
                });

            modelBuilder.Entity("ScpCv.Domain.Model.Scenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BigScreenMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BigScreenModeState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolumeState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder", "UpdatedAt");

                    b.ToTable("scenarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_scenarios_volume", "VolumeLevel >= 0 AND VolumeLevel <= 100");
                        });
                });

            modelBuilder.Entity("ScpCv.Domain.Model.StreamSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StreamIdentifier")
                        .IsUnique();

                    b.ToTable("stream_sources", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuperuser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.WorkerOwnership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastTransportHeartbeat")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUiProgress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogonSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessStartTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkerInstanceId")
                        .IsUnique();

                    b.HasIndex("TargetKind", "TargetId")
                        .IsUnique();

                    b.ToTable("worker_ownerships", (string)null);
                });

            modelBuilder.Entity("ScpCv.Domain.Model.ArtifactManifest", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.BackgroundAudioPlaylistItem", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScpCv.Domain.Model.BackgroundAudioState", "State")
                        .WithMany("Playlist")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.BackgroundAudioState", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaSource", "CurrentSource")
                        .WithMany()
                        .HasForeignKey("CurrentSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentSource");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaFolder", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaFolder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaPreparationJob", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaSource", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaFolder", "Folder")
                        .WithMany("Sources")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.PlaybackSession", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaSource", "MediaSource")
                        .WithMany()
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaSource");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.PptResource", b =>
                {
                    b.HasOne("ScpCv.Domain.Model.MediaSource", "Source")
                        .WithMany("PptResources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.BackgroundAudioState", b =>
                {
                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("ScpCv.Domain.Model.MediaSource", b =>
                {
                    b.Navigation("PptResources");
                });
#pragma warning restore 612, 618
        }
    }
}
