<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ScpCv.AudioWorker\ScpCv.AudioWorker.csproj" />
    <ProjectReference Include="..\..\src\ScpCv.Contracts\ScpCv.Contracts.csproj" />
    <ProjectReference Include="..\..\src\ScpCv.Domain\ScpCv.Domain.csproj" />
    <ProjectReference Include="..\..\src\ScpCv.PlayerWorker\ScpCv.PlayerWorker.csproj" />
    <ProjectReference Include="..\..\src\ScpCv.PowerPointHost\ScpCv.PowerPointHost.csproj" />
    <ProjectReference Include="..\..\src\ScpCv.Supervisor\ScpCv.Supervisor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
