# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scp_cv.v1 import control_pb2 as scp__cv_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scp_cv/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlaybackControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRuntimeStatus = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/GetRuntimeStatus',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.RuntimeStatusRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.RuntimeStatusReply.FromString,
                _registered_method=True)
        self.ListDisplayTargets = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ListDisplayTargets',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.DisplayTargetsReply.FromString,
                _registered_method=True)
        self.OpenResource = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/OpenResource',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.OpenResourceRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ControlPptPage = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ControlPptPage',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.ControlPptPageRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ControlCurrentMedia = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ControlCurrentMedia',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.ControlMediaRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.OpenStream = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/OpenStream',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.OpenStreamRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.StopCurrentContent = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/StopCurrentContent',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.SelectDisplayTarget = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/SelectDisplayTarget',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.SelectDisplayTargetRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)


class PlaybackControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRuntimeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDisplayTargets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlPptPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlCurrentMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCurrentContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectDisplayTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybackControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRuntimeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeStatus,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.RuntimeStatusRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.RuntimeStatusReply.SerializeToString,
            ),
            'ListDisplayTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDisplayTargets,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.DisplayTargetsReply.SerializeToString,
            ),
            'OpenResource': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenResource,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.OpenResourceRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'ControlPptPage': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlPptPage,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.ControlPptPageRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'ControlCurrentMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlCurrentMedia,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.ControlMediaRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'OpenStream': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenStream,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.OpenStreamRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'StopCurrentContent': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCurrentContent,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'SelectDisplayTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectDisplayTarget,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.SelectDisplayTargetRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scp_cv.v1.PlaybackControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scp_cv.v1.PlaybackControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybackControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRuntimeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/GetRuntimeStatus',
            scp__cv_dot_v1_dot_control__pb2.RuntimeStatusRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.RuntimeStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDisplayTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ListDisplayTargets',
            scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.DisplayTargetsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/OpenResource',
            scp__cv_dot_v1_dot_control__pb2.OpenResourceRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlPptPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ControlPptPage',
            scp__cv_dot_v1_dot_control__pb2.ControlPptPageRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlCurrentMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ControlCurrentMedia',
            scp__cv_dot_v1_dot_control__pb2.ControlMediaRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/OpenStream',
            scp__cv_dot_v1_dot_control__pb2.OpenStreamRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCurrentContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/StopCurrentContent',
            scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectDisplayTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/SelectDisplayTarget',
            scp__cv_dot_v1_dot_control__pb2.SelectDisplayTargetRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
