# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scp_cv.v1 import control_pb2 as scp__cv_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scp_cv/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlaybackControlServiceStub(object):
    """──────────────────────────────────────────────────────────────
    PlaybackControlService — SCP-cv 统一播放控制 gRPC 服务

    该服务随 Django 进程启动（django-socio-grpc 共宿主），默认端口 50051。
    外部系统（中控、自动化脚本等）通过本服务远程操控大屏播放内容。

    功能分组：
    源管理     — 打开 / 关闭媒体源（PPT、视频、WebRTC 流等）
    播放控制   — 播放、暂停、停止
    内容导航   — PPT 翻页、视频/音频时间跳转
    状态查询   — 运行时概览、详细播放状态
    显示器管理 — 查询可用屏幕、切换单屏/拼接模式
    ──────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSource = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/OpenSource',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.OpenSourceRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.CloseSource = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/CloseSource',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.CloseSourceRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ControlPlayback = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ControlPlayback',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.ControlPlaybackRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.NavigateContent = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/NavigateContent',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.NavigateContentRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.GetRuntimeStatus = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/GetRuntimeStatus',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.WindowRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.RuntimeStatusReply.FromString,
                _registered_method=True)
        self.GetPlaybackState = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/GetPlaybackState',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.WindowRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.PlaybackStateReply.FromString,
                _registered_method=True)
        self.ListDisplayTargets = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ListDisplayTargets',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.DisplayTargetsReply.FromString,
                _registered_method=True)
        self.SelectDisplayTarget = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/SelectDisplayTarget',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.SelectDisplayTargetRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ListSources = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ListSources',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.ListSourcesRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.ListSourcesReply.FromString,
                _registered_method=True)
        self.AddLocalPathSource = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/AddLocalPathSource',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.AddLocalPathSourceRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.SourceReply.FromString,
                _registered_method=True)
        self.AddWebUrlSource = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/AddWebUrlSource',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.AddWebUrlSourceRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.SourceReply.FromString,
                _registered_method=True)
        self.DeleteSource = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/DeleteSource',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.DeleteSourceRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ToggleLoop = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ToggleLoop',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.ToggleLoopRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.SetSpliceMode = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/SetSpliceMode',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.SetSpliceModeRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.SpliceModeReply.FromString,
                _registered_method=True)
        self.ShowWindowIds = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/ShowWindowIds',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)
        self.GetAllSessionSnapshots = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/GetAllSessionSnapshots',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.AllSessionSnapshotsReply.FromString,
                _registered_method=True)
        self.WatchPlaybackState = channel.unary_stream(
                '/scp_cv.v1.PlaybackControlService/WatchPlaybackState',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.PlaybackStateEvent.FromString,
                _registered_method=True)
        self.StopCurrentContent = channel.unary_unary(
                '/scp_cv.v1.PlaybackControlService/StopCurrentContent',
                request_serializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
                response_deserializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
                _registered_method=True)


class PlaybackControlServiceServicer(object):
    """──────────────────────────────────────────────────────────────
    PlaybackControlService — SCP-cv 统一播放控制 gRPC 服务

    该服务随 Django 进程启动（django-socio-grpc 共宿主），默认端口 50051。
    外部系统（中控、自动化脚本等）通过本服务远程操控大屏播放内容。

    功能分组：
    源管理     — 打开 / 关闭媒体源（PPT、视频、WebRTC 流等）
    播放控制   — 播放、暂停、停止
    内容导航   — PPT 翻页、视频/音频时间跳转
    状态查询   — 运行时概览、详细播放状态
    显示器管理 — 查询可用屏幕、切换单屏/拼接模式
    ──────────────────────────────────────────────────────────────
    """

    def OpenSource(self, request, context):
        """── 源管理 ──

        打开指定媒体源并开始播放。
        通过 media_source_id 指定要打开的 MediaSource 记录。
        若当前已有播放中的源，会先自动关闭再打开新源。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSource(self, request, context):
        """关闭当前正在播放的媒体源。
        将播放状态归零，播放器窗口回到待命状态。
        无需指定 ID，始终作用于当前活跃的源。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlPlayback(self, request, context):
        """── 播放控制 ──

        对当前源执行播放/暂停/停止操作。
        已有源打开时有效；无活跃源时返回错误。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NavigateContent(self, request, context):
        """── 内容导航 ──

        PPT 翻页（上/下/跳转指定页）或 视频/音频时间跳转。
        仅在相应源类型激活时生效：PPT 支持 NEXT/PREV/GOTO，
        视频/音频支持 SEEK；源类型不匹配的动作会被忽略。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeStatus(self, request, context):
        """── 状态查询 ──

        获取系统运行时概览（当前源类型、播放状态、显示模式、gRPC 地址等）。
        适合中控面板轮询或健康检查使用。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaybackState(self, request, context):
        """获取详细播放状态，包含 PPT 页码、视频进度等子类型特有信息。
        比 GetRuntimeStatus 更完整，适合需要渲染进度条/页码的客户端。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDisplayTargets(self, request, context):
        """── 显示器管理 ──

        列出当前主机上所有可用显示器及其分辨率、坐标信息。
        同时返回自动拼接标签（如 "Display 1 + Display 2"）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectDisplayTarget(self, request, context):
        """切换显示目标：可选 single（单屏）或 left_right_splice（左右拼接）。
        切换后播放器窗口会自动重新定位到目标屏幕。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSources(self, request, context):
        """── 源管理（CRUD） ──

        列出所有可用媒体源。可选按类型过滤。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLocalPathSource(self, request, context):
        """通过本地文件路径注册媒体源（文件上传保留 HTTP 端点）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddWebUrlSource(self, request, context):
        """通过 URL 添加网页类型媒体源。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSource(self, request, context):
        """删除指定媒体源。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleLoop(self, request, context):
        """── 扩展播放控制 ──

        切换指定窗口的循环播放模式。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpliceMode(self, request, context):
        """设置窗口 1+2 的左右拼接模式。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowWindowIds(self, request, context):
        """触发所有窗口显示 5 秒窗口 ID 叠加标识。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllSessionSnapshots(self, request, context):
        """── 扩展状态查询 ──

        获取所有窗口的播放会话快照列表。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchPlaybackState(self, request, context):
        """── 实时推送（替代 SSE） ──

        服务端流式推送播放状态变更，客户端通过此 RPC 代替 SSE 订阅实时更新。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCurrentContent(self, request, context):
        """── 兼容接口 ──

        停止当前播放内容（等价于 CloseSource，保留供旧版客户端调用）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybackControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSource': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSource,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.OpenSourceRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'CloseSource': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSource,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.CloseSourceRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'ControlPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlPlayback,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.ControlPlaybackRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'NavigateContent': grpc.unary_unary_rpc_method_handler(
                    servicer.NavigateContent,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.NavigateContentRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'GetRuntimeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeStatus,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.WindowRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.RuntimeStatusReply.SerializeToString,
            ),
            'GetPlaybackState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaybackState,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.WindowRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.PlaybackStateReply.SerializeToString,
            ),
            'ListDisplayTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDisplayTargets,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.DisplayTargetsReply.SerializeToString,
            ),
            'SelectDisplayTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectDisplayTarget,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.SelectDisplayTargetRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'ListSources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSources,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.ListSourcesRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.ListSourcesReply.SerializeToString,
            ),
            'AddLocalPathSource': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLocalPathSource,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.AddLocalPathSourceRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.SourceReply.SerializeToString,
            ),
            'AddWebUrlSource': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWebUrlSource,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.AddWebUrlSourceRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.SourceReply.SerializeToString,
            ),
            'DeleteSource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSource,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.DeleteSourceRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'ToggleLoop': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleLoop,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.ToggleLoopRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'SetSpliceMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpliceMode,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.SetSpliceModeRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.SpliceModeReply.SerializeToString,
            ),
            'ShowWindowIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowWindowIds,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
            'GetAllSessionSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSessionSnapshots,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.AllSessionSnapshotsReply.SerializeToString,
            ),
            'WatchPlaybackState': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchPlaybackState,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.PlaybackStateEvent.SerializeToString,
            ),
            'StopCurrentContent': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCurrentContent,
                    request_deserializer=scp__cv_dot_v1_dot_control__pb2.EmptyRequest.FromString,
                    response_serializer=scp__cv_dot_v1_dot_control__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scp_cv.v1.PlaybackControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scp_cv.v1.PlaybackControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybackControlService(object):
    """──────────────────────────────────────────────────────────────
    PlaybackControlService — SCP-cv 统一播放控制 gRPC 服务

    该服务随 Django 进程启动（django-socio-grpc 共宿主），默认端口 50051。
    外部系统（中控、自动化脚本等）通过本服务远程操控大屏播放内容。

    功能分组：
    源管理     — 打开 / 关闭媒体源（PPT、视频、WebRTC 流等）
    播放控制   — 播放、暂停、停止
    内容导航   — PPT 翻页、视频/音频时间跳转
    状态查询   — 运行时概览、详细播放状态
    显示器管理 — 查询可用屏幕、切换单屏/拼接模式
    ──────────────────────────────────────────────────────────────
    """

    @staticmethod
    def OpenSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/OpenSource',
            scp__cv_dot_v1_dot_control__pb2.OpenSourceRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/CloseSource',
            scp__cv_dot_v1_dot_control__pb2.CloseSourceRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ControlPlayback',
            scp__cv_dot_v1_dot_control__pb2.ControlPlaybackRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NavigateContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/NavigateContent',
            scp__cv_dot_v1_dot_control__pb2.NavigateContentRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/GetRuntimeStatus',
            scp__cv_dot_v1_dot_control__pb2.WindowRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.RuntimeStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaybackState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/GetPlaybackState',
            scp__cv_dot_v1_dot_control__pb2.WindowRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.PlaybackStateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDisplayTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ListDisplayTargets',
            scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.DisplayTargetsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectDisplayTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/SelectDisplayTarget',
            scp__cv_dot_v1_dot_control__pb2.SelectDisplayTargetRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ListSources',
            scp__cv_dot_v1_dot_control__pb2.ListSourcesRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.ListSourcesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLocalPathSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/AddLocalPathSource',
            scp__cv_dot_v1_dot_control__pb2.AddLocalPathSourceRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.SourceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddWebUrlSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/AddWebUrlSource',
            scp__cv_dot_v1_dot_control__pb2.AddWebUrlSourceRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.SourceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/DeleteSource',
            scp__cv_dot_v1_dot_control__pb2.DeleteSourceRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleLoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ToggleLoop',
            scp__cv_dot_v1_dot_control__pb2.ToggleLoopRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpliceMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/SetSpliceMode',
            scp__cv_dot_v1_dot_control__pb2.SetSpliceModeRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.SpliceModeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowWindowIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/ShowWindowIds',
            scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllSessionSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/GetAllSessionSnapshots',
            scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.AllSessionSnapshotsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchPlaybackState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/WatchPlaybackState',
            scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.PlaybackStateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCurrentContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scp_cv.v1.PlaybackControlService/StopCurrentContent',
            scp__cv_dot_v1_dot_control__pb2.EmptyRequest.SerializeToString,
            scp__cv_dot_v1_dot_control__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
