<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScpCv.Contracts\ScpCv.Contracts.csproj" />
    <ProjectReference Include="..\ScpCv.Domain\ScpCv.Domain.csproj" />
  </ItemGroup>

</Project>
