/*
 * Fluent UI System Icons 映射表（DESIGN.md §9 与生态包的关系）。
 *
 * 设计取舍：
 * 1. 业务侧延续既有名 token（`home_24_regular` 等）调用 `<FIcon name="…" />`，
 *    本表把它翻译为 @vicons/fluent 暴露的 Vue 组件（PascalCase 化的官方
 *    Fluent UI System Icons 名）。
 * 2. 渲染由 FIcon.vue 通过 `<n-icon><component :is /></n-icon>` 完成；本文件
 *    只负责映射，不直接渲染。
 * 3. `FluentIconName` 联合类型从 ICON_MAP 的键派生，保持全仓库类型契约不变。
 */
import type { Component } from 'vue';
import {
  Add24Regular,
  Add20Regular,
  Alert24Regular,
  AlertUrgent24Regular,
  Apps24Regular,
  AppsList24Regular,
  ArrowClockwise24Regular,
  ArrowClockwise20Regular,
  ArrowDownload24Regular,
  ArrowLeft24Regular,
  ArrowRight24Regular,
  ArrowMaximize24Regular,
  ArrowMinimize24Regular,
  ArrowRepeatAll24Regular,
  ArrowRepeatAllOff24Regular,
  ArrowReset24Regular,
  ArrowSwap24Regular,
  ArrowUpload24Regular,
  Checkmark16Filled,
  Checkmark20Regular,
  Checkmark24Regular,
  CheckmarkCircle24Filled,
  ChevronDown20Regular,
  ChevronUp20Regular,
  ChevronLeft20Regular,
  ChevronLeft24Regular,
  ChevronRight20Regular,
  ChevronRight24Regular,
  Circle24Regular,
  DarkTheme24Regular,
  Delete24Regular,
  Delete20Regular,
  Desktop24Regular,
  DesktopMac24Regular,
  Dismiss24Regular,
  Dismiss20Regular,
  Dismiss16Regular,
  Document24Regular,
  Edit24Regular,
  Edit20Regular,
  ErrorCircle24Filled,
  ErrorCircle20Filled,
  Eye24Regular,
  EyeOff24Regular,
  Filter24Regular,
  Folder24Regular,
  FullScreenMaximize24Regular,
  FullScreenMinimize24Regular,
  Globe24Regular,
  Home24Regular,
  Home24Filled,
  Image24Regular,
  Info24Regular,
  Layer24Regular,
  Layer24Filled,
  Library24Regular,
  Library24Filled,
  Link24Regular,
  Live24Regular,
  MoreHorizontal24Regular,
  MoreHorizontal20Regular,
  MusicNote224Regular,
  Navigation24Regular,
  Next24Regular,
  Open24Regular,
  Pause24Regular,
  Pause24Filled,
  Pin24Regular,
  Pin24Filled,
  PinOff24Regular,
  Play24Regular,
  Play24Filled,
  PlugDisconnected24Regular,
  Power24Regular,
  Previous24Regular,
  RadioButton24Regular,
  RadioButton24Filled,
  Search24Regular,
  Search20Regular,
  Settings24Regular,
  Settings24Filled,
  Speaker224Regular,
  Speaker220Regular,
  SpeakerMute24Regular,
  SpeakerMute20Regular,
  SpeakerOff24Regular,
  SpinnerIos20Regular,
  Star24Regular,
  Star24Filled,
  Stop24Regular,
  Subtract16Filled,
  Tv24Regular,
  Tv24Filled,
  Video24Regular,
  Warning24Filled,
  Warning20Filled,
  WeatherMoon24Regular,
  WeatherSunny24Regular,
} from '@vicons/fluent';

/**
 * token 名 → @vicons/fluent Vue 组件 静态映射。
 * 沿用业务层既有的 ~70 个 token 名，避免大面积改 props。
 */
export const ICON_MAP = {
  add_24_regular: Add24Regular,
  add_20_regular: Add20Regular,
  alert_24_regular: Alert24Regular,
  alert_urgent_24_regular: AlertUrgent24Regular,
  apps_list_24_regular: AppsList24Regular,
  apps_24_regular: Apps24Regular,
  arrow_clockwise_24_regular: ArrowClockwise24Regular,
  arrow_clockwise_20_regular: ArrowClockwise20Regular,
  arrow_download_24_regular: ArrowDownload24Regular,
  arrow_left_24_regular: ArrowLeft24Regular,
  arrow_right_24_regular: ArrowRight24Regular,
  arrow_maximize_24_regular: ArrowMaximize24Regular,
  arrow_minimize_24_regular: ArrowMinimize24Regular,
  arrow_repeat_all_24_regular: ArrowRepeatAll24Regular,
  arrow_repeat_all_off_24_regular: ArrowRepeatAllOff24Regular,
  arrow_reset_24_regular: ArrowReset24Regular,
  arrow_swap_24_regular: ArrowSwap24Regular,
  arrow_upload_24_regular: ArrowUpload24Regular,
  checkmark_16_filled: Checkmark16Filled,
  checkmark_20_regular: Checkmark20Regular,
  checkmark_24_regular: Checkmark24Regular,
  checkmark_circle_24_filled: CheckmarkCircle24Filled,
  chevron_down_20_regular: ChevronDown20Regular,
  chevron_up_20_regular: ChevronUp20Regular,
  chevron_left_20_regular: ChevronLeft20Regular,
  chevron_left_24_regular: ChevronLeft24Regular,
  chevron_right_20_regular: ChevronRight20Regular,
  chevron_right_24_regular: ChevronRight24Regular,
  dark_theme_24_regular: DarkTheme24Regular,
  delete_24_regular: Delete24Regular,
  delete_20_regular: Delete20Regular,
  desktop_24_regular: Desktop24Regular,
  desktop_mac_24_regular: DesktopMac24Regular,
  dismiss_24_regular: Dismiss24Regular,
  dismiss_20_regular: Dismiss20Regular,
  dismiss_16_regular: Dismiss16Regular,
  document_24_regular: Document24Regular,
  edit_24_regular: Edit24Regular,
  edit_20_regular: Edit20Regular,
  error_circle_24_filled: ErrorCircle24Filled,
  error_circle_20_filled: ErrorCircle20Filled,
  eye_24_regular: Eye24Regular,
  eye_off_24_regular: EyeOff24Regular,
  filter_24_regular: Filter24Regular,
  folder_24_regular: Folder24Regular,
  full_screen_maximize_24_regular: FullScreenMaximize24Regular,
  full_screen_minimize_24_regular: FullScreenMinimize24Regular,
  globe_24_regular: Globe24Regular,
  home_24_regular: Home24Regular,
  home_24_filled: Home24Filled,
  image_24_regular: Image24Regular,
  info_24_regular: Info24Regular,
  layer_24_regular: Layer24Regular,
  layer_24_filled: Layer24Filled,
  library_24_regular: Library24Regular,
  library_24_filled: Library24Filled,
  link_24_regular: Link24Regular,
  live_24_regular: Live24Regular,
  more_horizontal_24_regular: MoreHorizontal24Regular,
  more_horizontal_20_regular: MoreHorizontal20Regular,
  music_note_2_24_regular: MusicNote224Regular,
  navigation_24_regular: Navigation24Regular,
  next_24_regular: Next24Regular,
  previous_24_regular: Previous24Regular,
  open_24_regular: Open24Regular,
  pause_24_regular: Pause24Regular,
  pause_24_filled: Pause24Filled,
  pin_24_regular: Pin24Regular,
  pin_24_filled: Pin24Filled,
  pin_off_24_regular: PinOff24Regular,
  play_24_regular: Play24Regular,
  play_24_filled: Play24Filled,
  plug_disconnected_24_regular: PlugDisconnected24Regular,
  power_24_regular: Power24Regular,
  radio_button_24_regular: RadioButton24Regular,
  radio_button_24_filled: RadioButton24Filled,
  search_24_regular: Search24Regular,
  search_20_regular: Search20Regular,
  settings_24_regular: Settings24Regular,
  settings_24_filled: Settings24Filled,
  speaker_2_24_regular: Speaker224Regular,
  speaker_2_20_regular: Speaker220Regular,
  speaker_mute_24_regular: SpeakerMute24Regular,
  speaker_mute_20_regular: SpeakerMute20Regular,
  speaker_off_24_regular: SpeakerOff24Regular,
  spinner_ios_20_regular: SpinnerIos20Regular,
  star_24_regular: Star24Regular,
  star_24_filled: Star24Filled,
  stop_24_regular: Stop24Regular,
  subtract_16_filled: Subtract16Filled,
  tv_24_regular: Tv24Regular,
  tv_24_filled: Tv24Filled,
  video_24_regular: Video24Regular,
  warning_24_filled: Warning24Filled,
  warning_20_filled: Warning20Filled,
  weather_moon_24_regular: WeatherMoon24Regular,
  weather_sunny_24_regular: WeatherSunny24Regular,
} as const satisfies Record<string, Component>;

/** 业务侧使用的图标名 token 联合类型；新增图标先登记本表再使用。 */
export type FluentIconName = keyof typeof ICON_MAP;

/** 未登记名兜底：用通用圆形占位，避免布局抖动。 */
export const FALLBACK_ICON: Component = Circle24Regular;

/**
 * 解析图标名为 Vue 组件。
 * @param name 业务侧使用的图标 token；未登记时回退到 Circle24Regular
 * @return Vue 组件，可作为 <component :is> 使用
 */
export function resolveIcon(name: FluentIconName | string): Component {
  return (ICON_MAP as Record<string, Component>)[name] ?? FALLBACK_ICON;
}

/** 调试辅助：返回当前已登记的图标映射数量。 */
export function loadedIconCount(): number {
  return Object.keys(ICON_MAP).length;
}
