# Generated by Django 6.0.3 on 2026-04-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('file_kind', models.CharField(choices=[('ppt', 'PPT'), ('pptx', 'PPTX'), ('derived', '派生资源'), ('stream_config', '流配置')], db_index=True, max_length=32)),
                ('original_path', models.CharField(max_length=512)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('parse_state', models.CharField(choices=[('pending', '待解析'), ('processing', '解析中'), ('ready', '已就绪'), ('failed', '失败')], db_index=True, default='pending', max_length=32)),
                ('resource_state', models.CharField(choices=[('idle', '空闲'), ('opened', '已打开'), ('playing', '播放中'), ('stopped', '已停止'), ('archived', '已归档')], default='idle', max_length=32)),
                ('source_checksum', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-last_used_at', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('derived_resource_path', models.CharField(blank=True, max_length=512)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_document', to='resources.resourcefile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PresentationPageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('media_name', models.CharField(max_length=255)),
                ('media_kind', models.CharField(choices=[('video', '视频'), ('audio', '音频')], max_length=16)),
                ('media_path', models.CharField(max_length=512)),
                ('playback_state', models.CharField(choices=[('stopped', '停止'), ('playing', '播放中'), ('paused', '暂停')], default='stopped', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='resources.presentationdocument')),
            ],
            options={
                'ordering': ['page_number', 'sort_order', 'media_name'],
                'constraints': [models.UniqueConstraint(fields=('document', 'page_number', 'media_name'), name='unique_page_media_name')],
            },
        ),
    ]
