# Generated by Django 6.0.3 on 2026-04-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_kind', models.CharField(choices=[('none', '无'), ('stream', 'SRT 流')], default='none', max_length=16)),
                ('playback_state', models.CharField(choices=[('idle', '待机'), ('loading', '加载中'), ('playing', '播放中'), ('paused', '暂停'), ('stopped', '已停止'), ('error', '异常')], default='idle', max_length=16)),
                ('display_mode', models.CharField(choices=[('single', '单屏'), ('left_right_splice', '左右拼接')], default='single', max_length=24)),
                ('target_display_label', models.CharField(blank=True, max_length=255)),
                ('spliced_display_label', models.CharField(blank=True, max_length=255)),
                ('is_spliced', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('stream_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to='streams.streamsource')),
            ],
            options={
                'ordering': ['-last_updated_at'],
            },
        ),
    ]
