# Generated by Django 6.0.3 on 2026-04-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0002_alter_playbacksession_content_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ppt', 'PPT 演示文稿'), ('video', '视频'), ('audio', '音频'), ('image', '图片'), ('web', '网页'), ('custom_stream', '自定义流'), ('webrtc_stream', 'WebRTC 流')], db_index=True, max_length=24, verbose_name='源类型')),
                ('name', models.CharField(max_length=255, verbose_name='显示名称')),
                ('uri', models.CharField(help_text='文件绝对路径、URL 或流标识符', max_length=1024, verbose_name='资源地址')),
                ('uploaded_file', models.FileField(blank=True, help_text='通过 Web 上传的文件存储路径', upload_to='uploads/%Y%m%d/', verbose_name='上传文件')),
                ('stream_identifier', models.CharField(blank=True, db_index=True, help_text='WebRTC 流的 MediaMTX 路径标识', max_length=255, verbose_name='流标识符')),
                ('is_available', models.BooleanField(default=True, help_text='文件是否存在 / 流是否在线', verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '媒体源',
                'verbose_name_plural': '媒体源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='playbacksession',
            options={'ordering': ['-last_updated_at'], 'verbose_name': '播放会话', 'verbose_name_plural': '播放会话'},
        ),
        migrations.RemoveField(
            model_name='playbacksession',
            name='content_kind',
        ),
        migrations.RemoveField(
            model_name='playbacksession',
            name='stream_source',
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='command_args',
            field=models.JSONField(blank=True, default=dict, verbose_name='指令参数'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='current_slide',
            field=models.IntegerField(default=0, verbose_name='当前页码'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='duration_ms',
            field=models.BigIntegerField(default=0, verbose_name='总时长(ms)'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='pending_command',
            field=models.CharField(blank=True, choices=[('', '无'), ('open', '打开源'), ('play', '播放'), ('pause', '暂停'), ('stop', '停止'), ('close', '关闭'), ('seek', '跳转'), ('next', '下一页/下一项'), ('prev', '上一页/上一项'), ('goto', '跳转到指定页')], default='', max_length=32, verbose_name='待执行指令'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='position_ms',
            field=models.BigIntegerField(default=0, verbose_name='当前位置(ms)'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='total_slides',
            field=models.IntegerField(default=0, verbose_name='总页数'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='display_mode',
            field=models.CharField(choices=[('single', '单屏'), ('left_right_splice', '左右拼接')], default='single', max_length=24, verbose_name='显示模式'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='is_spliced',
            field=models.BooleanField(default=False, verbose_name='是否拼接'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='playback_state',
            field=models.CharField(choices=[('idle', '待机'), ('loading', '加载中'), ('playing', '播放中'), ('paused', '暂停'), ('stopped', '已停止'), ('error', '异常')], default='idle', max_length=16, verbose_name='播放状态'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='spliced_display_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='拼接显示器组'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='target_display_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='目标显示器'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='media_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to='playback.mediasource', verbose_name='当前媒体源'),
        ),
    ]
