# Generated by Django 6.0.3 on 2026-04-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0003_unified_media_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbacksession',
            name='loop_enabled',
            field=models.BooleanField(default=False, help_text='视频/音频播放完毕后是否自动重头播放', verbose_name='循环播放'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='pending_command',
            field=models.CharField(blank=True, choices=[('', '无'), ('open', '打开源'), ('play', '播放'), ('pause', '暂停'), ('stop', '停止'), ('close', '关闭'), ('seek', '跳转'), ('next', '下一页/下一项'), ('prev', '上一页/上一项'), ('goto', '跳转到指定页'), ('set_loop', '设置循环播放')], default='', max_length=32, verbose_name='待执行指令'),
        ),
    ]
