# Generated by Django 6.0.3 on 2026-04-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0004_add_loop_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasource',
            name='source_type',
            field=models.CharField(choices=[('ppt', 'PPT 演示文稿'), ('video', '视频'), ('audio', '音频'), ('image', '图片'), ('web', '网页'), ('custom_stream', '自定义流'), ('rtsp_stream', 'RTSP 流')], db_index=True, max_length=24, verbose_name='源类型'),
        ),
        migrations.AlterField(
            model_name='mediasource',
            name='stream_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='RTSP 流的 MediaMTX 路径标识', max_length=255, verbose_name='流标识符'),
        ),
    ]
