# Generated by Django 6.0.3 on 2026-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0005_alter_mediasource_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasource',
            name='source_type',
            field=models.CharField(choices=[('ppt', 'PPT 演示文稿'), ('video', '视频'), ('audio', '音频'), ('image', '图片'), ('web', '网页'), ('custom_stream', '自定义流'), ('rtsp_stream', 'RTSP 流'), ('srt_stream', 'SRT 流')], db_index=True, max_length=24, verbose_name='源类型'),
        ),
    ]
