# Generated by Django 6.0.3 on 2026-04-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0006_alter_mediasource_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbacksession',
            name='window_id',
            field=models.PositiveSmallIntegerField(default=1, help_text='输出窗口编号，1-4 对应四个输出显示器', unique=True, verbose_name='窗口编号'),
            preserve_default=False,
        ),
    ]
