# Generated by Django 6.0.3 on 2026-04-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0007_add_window_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbacksession',
            name='pending_command',
            field=models.CharField(blank=True, choices=[('', '无'), ('open', '打开源'), ('play', '播放'), ('pause', '暂停'), ('stop', '停止'), ('close', '关闭'), ('seek', '跳转'), ('next', '下一页/下一项'), ('prev', '上一页/上一项'), ('goto', '跳转到指定页'), ('set_loop', '设置循环播放'), ('show_id', '显示窗口 ID')], default='', max_length=32, verbose_name='待执行指令'),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='预案名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_splice_mode', models.BooleanField(default=False, help_text='启用后窗口 1+2 拼接显示同一源，窗口 2 配置被忽略', verbose_name='拼接模式')),
                ('window1_autoplay', models.BooleanField(default=True, verbose_name='窗口 1 自动播放')),
                ('window1_resume', models.BooleanField(default=True, help_text='相同源已打开时保留当前进度，否则从头播放', verbose_name='窗口 1 保留进度')),
                ('window2_autoplay', models.BooleanField(default=True, verbose_name='窗口 2 自动播放')),
                ('window2_resume', models.BooleanField(default=True, help_text='相同源已打开时保留当前进度，否则从头播放', verbose_name='窗口 2 保留进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('window1_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios_as_w1', to='playback.mediasource', verbose_name='窗口 1 媒体源')),
                ('window2_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios_as_w2', to='playback.mediasource', verbose_name='窗口 2 媒体源')),
            ],
            options={
                'verbose_name': '预案',
                'verbose_name_plural': '预案',
                'ordering': ['-updated_at'],
            },
        ),
    ]
