# Generated by Django 6.0.3 on 2026-04-29 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0011_remove_window1_fullscreen_to_window2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('splice_screen', '拼接屏'), ('tv_left', '电视左'), ('tv_right', '电视右')], max_length=24, unique=True, verbose_name='设备类型')),
                ('is_powered_on', models.BooleanField(default=False, verbose_name='是否开机')),
                ('address', models.CharField(blank=True, help_text='IP 或串口地址，待后续实现', max_length=255, verbose_name='设备地址')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备端点',
                'verbose_name_plural': '设备端点',
                'ordering': ['device_type'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('big_screen_mode', models.CharField(choices=[('single', '单屏'), ('double', '双屏')], default='single', max_length=8, verbose_name='当前大屏模式')),
                ('volume_level', models.IntegerField(default=100, verbose_name='系统音量（0-100）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
            options={
                'verbose_name': '运行状态',
                'verbose_name_plural': '运行状态',
            },
        ),
        migrations.AlterModelOptions(
            name='playbacksession',
            options={'ordering': ['window_id'], 'verbose_name': '播放会话', 'verbose_name_plural': '播放会话'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['-sort_order', '-updated_at'], 'verbose_name': '预案', 'verbose_name_plural': '预案'},
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='window1_autoplay',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='window1_resume',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='window1_source',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='window2_autoplay',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='window2_resume',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='window2_source',
        ),
        migrations.AddField(
            model_name='mediasource',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='临时源过期后自动清理', null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='mediasource',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='文件大小（字节）'),
        ),
        migrations.AddField(
            model_name='mediasource',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='临时源在切换离开后自动删除', verbose_name='是否临时源'),
        ),
        migrations.AddField(
            model_name='mediasource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='存储 PPT 解析资源 ID 等扩展信息', verbose_name='扩展元数据'),
        ),
        migrations.AddField(
            model_name='mediasource',
            name='mime_type',
            field=models.CharField(blank=True, max_length=127, verbose_name='MIME 类型'),
        ),
        migrations.AddField(
            model_name='mediasource',
            name='original_filename',
            field=models.CharField(blank=True, help_text='上传时的原始文件名，用于下载', max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='is_muted',
            field=models.BooleanField(default=False, verbose_name='是否静音'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='volume',
            field=models.IntegerField(default=100, verbose_name='音量（0-100）'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='big_screen_mode',
            field=models.CharField(blank=True, choices=[('single', '单屏'), ('double', '双屏')], default='single', help_text='仅当 big_screen_mode_state=set 时生效', max_length=8, verbose_name='大屏模式'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='big_screen_mode_state',
            field=models.CharField(choices=[('unset', '未设置（保持原有）'), ('empty', '清空（黑屏）'), ('set', '已设置（使用绑定源）')], default='unset', max_length=8, verbose_name='大屏模式状态'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数值越大越靠前，支持置顶', verbose_name='排序权重'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='volume_level',
            field=models.IntegerField(default=100, help_text='仅当 volume_state=set 时生效', verbose_name='音量等级（0-100）'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='volume_state',
            field=models.CharField(choices=[('unset', '未设置（保持原有）'), ('empty', '清空（黑屏）'), ('set', '已设置（使用绑定源）')], default='unset', max_length=8, verbose_name='音量状态'),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='pending_command',
            field=models.CharField(blank=True, choices=[('', '无'), ('open', '打开源'), ('play', '播放'), ('pause', '暂停'), ('stop', '停止'), ('close', '关闭'), ('seek', '跳转'), ('next', '下一页/下一项'), ('prev', '上一页/上一项'), ('goto', '跳转到指定页'), ('set_loop', '设置循环播放'), ('set_volume', '设置音量'), ('set_mute', '设置静音'), ('show_id', '显示窗口 ID')], default='', max_length=32, verbose_name='待执行指令'),
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件夹名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='playback.mediafolder', verbose_name='父文件夹')),
            ],
            options={
                'verbose_name': '媒体文件夹',
                'verbose_name_plural': '媒体文件夹',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediasource',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='playback.mediafolder', verbose_name='所属文件夹'),
        ),
        migrations.CreateModel(
            name='PptResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveIntegerField(verbose_name='页码（从 1 开始）')),
                ('slide_image', models.CharField(blank=True, max_length=512, verbose_name='幻灯片 PNG 路径')),
                ('next_slide_image', models.CharField(blank=True, max_length=512, verbose_name='下一页 PNG 路径')),
                ('speaker_notes', models.TextField(blank=True, default='', verbose_name='演讲者备注/提词器文本')),
                ('has_media', models.BooleanField(default=False, help_text='该页是否包含视频/音频媒体对象', verbose_name='是否包含媒体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppt_resources', to='playback.mediasource', verbose_name='关联 PPT 源')),
            ],
            options={
                'verbose_name': 'PPT 资源',
                'verbose_name_plural': 'PPT 资源',
                'ordering': ['source', 'page_index'],
                'unique_together': {('source', 'page_index')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_id', models.PositiveSmallIntegerField(help_text='1-4 对应四个输出窗口', verbose_name='窗口编号')),
                ('source_state', models.CharField(choices=[('unset', '未设置（保持原有）'), ('empty', '清空（黑屏）'), ('set', '已设置（使用绑定源）')], default='unset', max_length=8, verbose_name='内容状态')),
                ('autoplay', models.BooleanField(default=True, help_text='仅当 source_state=set 时生效', verbose_name='自动播放')),
                ('resume', models.BooleanField(default=True, help_text='相同源已打开时保留当前进度，否则从头播放', verbose_name='保留进度')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='playback.scenario', verbose_name='所属预案')),
                ('source', models.ForeignKey(blank=True, help_text='仅当 source_state=set 时生效', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_targets', to='playback.mediasource', verbose_name='绑定媒体源')),
            ],
            options={
                'verbose_name': '预案窗口目标',
                'verbose_name_plural': '预案窗口目标',
                'ordering': ['window_id'],
                'unique_together': {('scenario', 'window_id')},
            },
        ),
    ]
