# Generated by OpenCode on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0012_expand_models_for_full_rewrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pptresource',
            name='media_items',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='当前页视频/音频对象列表，供前端逐项控制',
                verbose_name='页面媒体清单',
            ),
        ),
        migrations.AlterField(
            model_name='playbacksession',
            name='pending_command',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '无'),
                    ('open', '打开源'),
                    ('play', '播放'),
                    ('pause', '暂停'),
                    ('stop', '停止'),
                    ('close', '关闭'),
                    ('seek', '跳转'),
                    ('next', '下一页/下一项'),
                    ('prev', '上一页/上一项'),
                    ('goto', '跳转到指定页'),
                    ('set_loop', '设置循环播放'),
                    ('set_volume', '设置音量'),
                    ('set_mute', '设置静音'),
                    ('ppt_media', '控制 PPT 当前页媒体'),
                    ('show_id', '显示窗口 ID'),
                ],
                default='',
                max_length=32,
                verbose_name='待执行指令',
            ),
        ),
    ]
