# Generated by OpenCode on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0013_ppt_media_items_and_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimestate',
            name='volume_muted',
            field=models.BooleanField(default=False, verbose_name='系统是否静音'),
        ),
    ]
