# Generated by Django 6.0.3 on 2026-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0014_runtime_volume_muted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceendpoint",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="IP 或串口地址",
                max_length=255,
                verbose_name="设备地址",
            ),
        ),
    ]
