# Generated by Django 6.0.3 on 2026-05-06 06:33

from django.db import migrations, models


def migrate_scenario_targets_to_json(apps, schema_editor):
    Scenario = apps.get_model("playback", "Scenario")
    ScenarioTarget = apps.get_model("playback", "ScenarioTarget")

    for scenario in Scenario.objects.all():
        targets = []
        for target in ScenarioTarget.objects.filter(scenario_id=scenario.pk).order_by("window_id"):
            targets.append({
                "window_id": int(target.window_id),
                "source_state": str(target.source_state),
                "source_id": int(target.source_id) if target.source_id else None,
                "autoplay": bool(target.autoplay),
                "resume": bool(target.resume),
            })
        scenario.targets = targets
        scenario.save(update_fields=["targets"])


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0015_alter_deviceendpoint_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceEndpoint",
        ),
        migrations.RemoveField(
            model_name="pptresource",
            name="has_media",
        ),
        migrations.RemoveField(
            model_name="pptresource",
            name="next_slide_image",
        ),
        migrations.AddField(
            model_name="scenario",
            name="targets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="四窗口目标列表，元素包含 window_id、source_state、source_id、autoplay、resume",
                verbose_name="窗口目标配置",
            ),
        ),
        migrations.RunPython(migrate_scenario_targets_to_json, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="ScenarioTarget",
        ),
    ]
