# Generated by Django 6.0.3 on 2026-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "playback",
            "0016_delete_deviceendpoint_alter_scenariotarget_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mediasource",
            name="keep_alive",
            field=models.BooleanField(
                default=True,
                help_text="仅对网页源（source_type=web）有意义；为 True 时播放器在系统启动阶段会预加载该网页并保持后台活跃，切换到该源时无需再次发起首次加载，可显著降低呈现延迟。其它源类型保留默认 True，但暂不参与预热逻辑。",
                verbose_name="保持活跃",
            ),
        ),
    ]
