# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0017_add_media_source_keep_alive"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbacksession",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="播放错误说明"),
        ),
    ]
