# Generated by Django 6.0.3 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0018_playbacksession_error_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediasource",
            name="keep_alive",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "仅对网页源（source_type=web）有意义；为 True 时播放器会在启动阶段预加载该网页，"
                    "切换到该源时可复用已加载的 WebView，降低首屏呈现延迟。"
                    "其它源类型保留默认 True，但暂不参与预热逻辑。"
                ),
                verbose_name="预热",
            ),
        ),
    ]
