# Generated by Django 6.0.3 on 2026-05-28 15:31

from django.db import migrations, models


def disable_legacy_non_web_preheat(apps, _schema_editor):
    """旧版本中非网页源的 keep_alive=True 只是无效默认值，升级时保持旧语义。"""
    media_source = apps.get_model("playback", "MediaSource")
    media_source.objects.exclude(source_type="web").update(keep_alive=False)


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0021_add_wps_ppt_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediasource",
            name="keep_alive",
            field=models.BooleanField(
                default=True,
                help_text="为 True 时播放器会在启动阶段按源类型建立后台预热资源；切换到该源时优先复用已加载资源，降低现场呈现延迟。",
                verbose_name="预热",
            ),
        ),
        migrations.RunPython(disable_legacy_non_web_preheat, migrations.RunPython.noop),
    ]
