# Generated by Django 6.0.3 on 2026-05-31 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0022_alter_mediasource_keep_alive"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundAudioPlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_audio_playlist_items",
                        to="playback.mediasource",
                        verbose_name="音频源",
                    ),
                ),
            ],
            options={
                "verbose_name": "背景音频播放列表项",
                "verbose_name_plural": "背景音频播放列表项",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BackgroundAudioState",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "playback_state",
                    models.CharField(
                        choices=[
                            ("idle", "待机"),
                            ("loading", "加载中"),
                            ("playing", "播放中"),
                            ("paused", "暂停"),
                            ("stopped", "已停止"),
                            ("error", "异常"),
                        ],
                        default="idle",
                        max_length=16,
                        verbose_name="播放状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="播放错误说明"
                    ),
                ),
                (
                    "position_ms",
                    models.BigIntegerField(default=0, verbose_name="当前位置(ms)"),
                ),
                (
                    "duration_ms",
                    models.BigIntegerField(default=0, verbose_name="总时长(ms)"),
                ),
                (
                    "volume",
                    models.IntegerField(default=70, verbose_name="音量（0-100）"),
                ),
                (
                    "is_muted",
                    models.BooleanField(default=False, verbose_name="是否静音"),
                ),
                (
                    "loop_enabled",
                    models.BooleanField(default=True, verbose_name="列表循环播放"),
                ),
                (
                    "pending_command",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "无"),
                            ("open", "打开音频源"),
                            ("play", "播放"),
                            ("pause", "暂停"),
                            ("stop", "停止"),
                            ("seek", "跳转"),
                            ("set_loop", "设置循环播放"),
                            ("set_volume", "设置音量"),
                            ("set_mute", "设置静音"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="待执行指令",
                    ),
                ),
                (
                    "command_args",
                    models.JSONField(blank=True, default=dict, verbose_name="指令参数"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新"),
                ),
                (
                    "current_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="background_audio_states",
                        to="playback.mediasource",
                        verbose_name="当前音频源",
                    ),
                ),
            ],
            options={
                "verbose_name": "背景音频状态",
                "verbose_name_plural": "背景音频状态",
            },
        ),
    ]
