# Generated by Django 6.0.3 on 2026-08-29 21:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_background_command(apps, _schema_editor) -> None:
    """将旧 BackgroundAudioState 单槽命令复制到新持久队列。"""
    State = apps.get_model("playback", "BackgroundAudioState")
    CommandRecord = apps.get_model("playback", "BackgroundAudioCommandRecord")
    for state in State.objects.exclude(pending_command=""):
        CommandRecord.objects.create(
            state_id=state.pk,
            command=state.pending_command,
            command_args=dict(state.command_args or {}),
            status="pending",
        )


def remove_migrated_background_commands(apps, _schema_editor) -> None:
    """回滚时清理新队列表数据。"""
    apps.get_model("playback", "BackgroundAudioCommandRecord").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0027_alter_mediasource_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundAudioCommandRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        choices=[
                            ("", "无"),
                            ("open", "打开音频源"),
                            ("play", "播放"),
                            ("pause", "暂停"),
                            ("stop", "停止"),
                            ("seek", "跳转"),
                            ("set_loop", "设置循环播放"),
                            ("set_volume", "设置音量"),
                            ("set_mute", "设置静音"),
                        ],
                        max_length=32,
                        verbose_name="播放指令",
                    ),
                ),
                (
                    "command_args",
                    models.JSONField(blank=True, default=dict, verbose_name="指令参数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待领取"), ("processing", "处理中")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "claimed_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="领取消费者",
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="领取时间"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="尝试次数"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="最后错误"),
                ),
            ],
            options={
                "verbose_name": "背景音频指令队列项",
                "verbose_name_plural": "背景音频指令队列项",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="playbackcommandrecord",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0, verbose_name="尝试次数"),
        ),
        migrations.AddField(
            model_name="playbackcommandrecord",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="领取时间"),
        ),
        migrations.AddField(
            model_name="playbackcommandrecord",
            name="claimed_by",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="领取消费者"
            ),
        ),
        migrations.AddField(
            model_name="playbackcommandrecord",
            name="last_error",
            field=models.TextField(blank=True, default="", verbose_name="最后错误"),
        ),
        migrations.AddField(
            model_name="playbackcommandrecord",
            name="status",
            field=models.CharField(
                choices=[("pending", "待领取"), ("processing", "处理中")],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="处理状态",
            ),
        ),
        migrations.AddIndex(
            model_name="playbackcommandrecord",
            index=models.Index(
                fields=["session", "status", "id"], name="playback_cmd_status_idx"
            ),
        ),
        migrations.AddField(
            model_name="backgroundaudiocommandrecord",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="command_queue",
                to="playback.backgroundaudiostate",
                verbose_name="背景音频状态",
            ),
        ),
        migrations.RunPython(
            migrate_legacy_background_command,
            remove_migrated_background_commands,
        ),
        migrations.AddIndex(
            model_name="backgroundaudiocommandrecord",
            index=models.Index(fields=["state", "id"], name="bg_audio_cmd_state_idx"),
        ),
        migrations.AddIndex(
            model_name="backgroundaudiocommandrecord",
            index=models.Index(
                fields=["state", "status", "id"], name="bg_audio_cmd_status_idx"
            ),
        ),
    ]
