# Generated by Django 6.0.3 on 2026-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0028_backgroundaudiocommandrecord_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE playback_playbacksession SET display_mode = 'single' WHERE display_mode <> 'single'",
            migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="playbacksession",
            name="is_spliced",
        ),
        migrations.RemoveField(
            model_name="playbacksession",
            name="spliced_display_label",
        ),
        migrations.AlterField(
            model_name="playbacksession",
            name="display_mode",
            field=models.CharField(
                choices=[("single", "单屏")],
                default="single",
                max_length=24,
                verbose_name="显示模式",
            ),
        ),
    ]
