# Generated by Django 6.0.3 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playback", "0029_remove_playbacksession_is_spliced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbacksession",
            name="playback_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "无"),
                    ("powerpoint", "PowerPoint"),
                    ("pdf", "PDF"),
                ],
                default="",
                help_text="由播放器按当前实际适配器上报，不表示媒体源的首选模式",
                max_length=16,
                verbose_name="演示文稿实际放映模式",
            ),
        ),
    ]
